version: "2"             # ← mandatory in v2 configs :contentReference[oaicite:0]{index=0}

run:
  timeout: 5m
  tests: true            # analyse both production and *_test.go files

linters:
  enable:
    - errcheck           # unchecked-error detector :contentReference[oaicite:1]{index=1}
    - govet              # wrapper around the standard `go vet` passes :contentReference[oaicite:2]{index=2}
    - ineffassign        # flags assignments whose results are never used :contentReference[oaicite:3]{index=3}
    - staticcheck        # now *also* contains all gosimple/stylecheck rules :contentReference[oaicite:4]{index=4}
    - unused             # reports unused consts, vars, funcs & types :contentReference[oaicite:5]{index=5}

formatters:
  enable:
    - gofmt              # checks code is `gofmt`-ed (autofix available) :contentReference[oaicite:6]{index=6}

issues:
  max-same-issues: 0
