name: Development Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  run-shared-checks:
    uses: ./.github/workflows/shared-go-checks.yml
    with:
      go-version: '1.21'
      run-race-detector: true
      run-coverage: true
      upload-coverage: true
      full-security-scan: false
      fail-on-coverage-decrease: false
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}