name: Feature Branch Check

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  minimal-check:
    name: Minimal Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      
      - name: Verify dependencies
        run: go mod verify
      
      - name: Run basic tests
        run: go test -short -run='^Test' ./...
      
      - name: Verify build
        run: go build -v ./...